### PR TITLE
Templating

### PR DESCRIPTION
**Pull request by fratschi**

### CODE REVIEW

**Comment by fratschi** [comment]
Hi, i have added a basic support for templating (dynamic resposnes)

**Comment by mkruse83** [comment]
Where is the actual call to the template evaluation and response? I kind of don't see it.

**Review by mkruse83 — COMMENTED** [review]
Where is the actual call to the template evaluation and response? I kind of don't see it.

**Comment by fratschi** [comment]
> Where is the actual call to the template evaluation and response? I kind of don't see it.

oh.. iv'e forgot the push... please look at handler.go  method reply... SORRY!

**Review by mkruse83 — APPROVED** [review]

**Review by mkruse83 — APPROVED** [review]

**Pull request merged**
